version: "3.4"

services:
  aqc-service-app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.cpu
      target: dev
    image: aqc-service-app
    container_name: aqc-service-app
    restart: always
    volumes:
        - ./:/root/yolact_edge/
    ports:
      - "8000:8000"
